import type { CareBridgeState } from "./types";

const today = new Date();
const dateFromNow = (days: number) => {
  const value = new Date(today);
  value.setDate(value.getDate() + days);
  return value.toISOString();
};

export const initialState: CareBridgeState = {
  activePatientId: "srey-mom",
  language: "en",
  patients: [
    {
      id: "srey-mom",
      name: "Srey Mom",
      phone: "012 555 017",
      surgery: "Appendix surgery",
      surgeryDate: dateFromNow(-7),
      recoveryDay: 7,
      status: "red",
      reasons: ["Pain getting worse", "Increasing redness", "Unusual discharge"],
      nextCheckIn: dateFromNow(0),
      followUpDate: dateFromNow(3),
      medication: "Amoxicillin · twice daily",
      lastResponseAt: dateFromNow(-1),
      responseMinutes: 12,
      followUpStage: "contacted",
      escalated: true,
      nurseNote: "Patient contacted at 10:30. Pain increased since yesterday.",
    },
    {
      id: "dara",
      name: "Dara",
      phone: "011 204 882",
      surgery: "Hernia repair",
      surgeryDate: dateFromNow(-4),
      recoveryDay: 4,
      status: "red",
      reasons: ["Fever", "Wound swelling"],
      nextCheckIn: dateFromNow(1),
      followUpDate: dateFromNow(5),
      medication: "Paracetamol · when needed",
      lastResponseAt: dateFromNow(-1),
      responseMinutes: 26,
      followUpStage: "pending",
      escalated: false,
    },
    {
      id: "pisey",
      name: "Pisey",
      phone: "096 336 410",
      surgery: "Gallbladder surgery",
      surgeryDate: dateFromNow(-14),
      recoveryDay: 14,
      status: "yellow",
      reasons: ["Pain unchanged"],
      nextCheckIn: dateFromNow(3),
      followUpDate: dateFromNow(7),
      medication: "Ibuprofen · with food",
      lastResponseAt: dateFromNow(-2),
      responseMinutes: 45,
      followUpStage: "pending",
      escalated: false,
    },
    {
      id: "sophea",
      name: "Sophea",
      phone: "010 889 122",
      surgery: "Caesarean section",
      surgeryDate: dateFromNow(-10),
      recoveryDay: 10,
      status: "green",
      reasons: ["Recovering as expected"],
      nextCheckIn: dateFromNow(4),
      followUpDate: dateFromNow(10),
      medication: "Iron supplement · daily",
      lastResponseAt: dateFromNow(-1),
      responseMinutes: 18,
      followUpStage: "resolved",
      escalated: false,
    },
    {
      id: "vanna",
      name: "Vanna",
      phone: "017 905 320",
      surgery: "Knee procedure",
      surgeryDate: dateFromNow(-8),
      recoveryDay: 8,
      status: "no-response",
      reasons: ["Day 7 check-in not completed"],
      nextCheckIn: dateFromNow(-1),
      followUpDate: dateFromNow(6),
      medication: "Pain relief · twice daily",
      followUpStage: "pending",
      escalated: false,
    },
    {
      id: "chenda",
      name: "Chenda",
      phone: "088 140 733",
      surgery: "Breast lump removal",
      surgeryDate: dateFromNow(-5),
      recoveryDay: 5,
      status: "no-response",
      reasons: ["Day 3 check-in not completed"],
      nextCheckIn: dateFromNow(-2),
      followUpDate: dateFromNow(4),
      medication: "Antibiotic · twice daily",
      followUpStage: "pending",
      escalated: false,
    },
  ],
  checkIns: [
    {
      id: "seed-checkin-1",
      patientId: "srey-mom",
      submittedAt: dateFromNow(-1),
      feeling: "worse",
      wound: ["redness", "discharge"],
      pain: "worse",
      fever: "not-sure",
      medicationTaken: true,
      result: "red",
      reasons: ["Pain getting worse", "Increasing redness", "Unusual discharge"],
      responseMinutes: 12,
      photoDataUrl: "/assets/wound-photo.jpg",
    },
    {
      id: "seed-checkin-2",
      patientId: "dara",
      submittedAt: dateFromNow(-1),
      feeling: "worse",
      wound: ["swelling"],
      pain: "same",
      fever: "yes",
      medicationTaken: true,
      result: "red",
      reasons: ["Fever", "Wound swelling"],
      responseMinutes: 26,
    },
    {
      id: "seed-checkin-3",
      patientId: "pisey",
      submittedAt: dateFromNow(-2),
      feeling: "same",
      wound: ["normal"],
      pain: "same",
      fever: "no",
      medicationTaken: true,
      result: "yellow",
      reasons: ["Pain unchanged"],
      responseMinutes: 45,
    },
    {
      id: "seed-checkin-4",
      patientId: "sophea",
      submittedAt: dateFromNow(-1),
      feeling: "better",
      wound: ["normal"],
      pain: "better",
      fever: "no",
      medicationTaken: true,
      result: "green",
      reasons: ["Recovering as expected"],
      responseMinutes: 18,
    },
  ],
  helpRequests: [],
};
